/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.references


import jooq_generated.tables.TestTable



/**
 * The table <code>public.test_table</code>.
 */
val TEST_TABLE = TestTable.TEST_TABLE
