/*
 * This file is generated by jOOQ.
 */
package jooq_generated.enums


import jooq_generated.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class TestEnum(@get:JvmName("literal") val literal: String) : EnumType {
    enum1("enum1"),
    enum2("enum2"),
    enum3("enum3");
    override fun getCatalog(): Catalog? = getSchema() == null ? null : getSchema().getCatalog()
    override fun getSchema(): Schema? = Public.PUBLIC
    override fun getName(): String? = "test_enum"
    override fun getLiteral(): String = literal
}
